services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  redis:
    image: redis:8
    ports:
      - "6379:6379"